export const ourProductArray = [
    {
      discountBtn: false,
      discountPrice: 40,
      trashIcon: false,
      heartIcon: true,
      eyeIcon: true,
      src: "/bread.png",
      Heading: "Breed Dry Dog Food",
      price: 100,
      star: 5,
      reviews: 35,
      colorDiv: false,
    },
    {
      discountBtn: false,
      discountPrice: 40,
      trashIcon: false,
      heartIcon: true,
      eyeIcon: true,
      src: "/camera.png",
      Heading: "CANON EOS DSLR Camera",
      price: 360,
      star: 5,
      reviews: 95,
      colorDiv: false
    }, 
    {
      discountBtn: false,
      discountPrice: 40,
      trashIcon: false,
      heartIcon: true,
      eyeIcon: true,
      src: "/laptop.png",
      Heading: "ASUS FHD Gaming Laptop",
      price: 700,
      star: 5,
      reviews: 325,
      colorDiv: false
    }, 
    {
      discountBtn: false,
      discountPrice: 40,
      trashIcon: false,
      heartIcon: true,
      eyeIcon: true,
      src: "/curology.png",
      Heading: "Curology Product Set",
      price: 145,
      star: 5,
      reviews: 35,
      colorDiv: false,
    }, 
    {
      discountBtn: true,
      discountPrice: "New",
      trashIcon: false,
      heartIcon: true,
      eyeIcon: true,
      src: "/car.png",
      Heading: "Kids Electric Car",
      price: 960,
      star: 5,
      reviews: 65,
      colorDiv: true,
      color1: "bg-black",
      color2: "red",
    },
    {
      discountBtn: false,
      discountPrice: 40,
      trashIcon: false,
      heartIcon: true,
      eyeIcon: true,
      src: "/shoes.png",
      Heading: "Jr. Zoom Soccer Cleats",
      price: 1160,
      star: 3,
      reviews: 35,
      colorDiv: true,
      color1: "bg-black",    
      color2: "red",
    },
    {
      discountBtn: true,
      discountPrice: "New",
      trashIcon: false,
      heartIcon: true,
      eyeIcon: true,
      src: "/usb.png",
      Heading: "GP11 Shooter USB Gamepad",
      price: 660,
      star: 4,
      reviews: 55,
      colorDiv: true,
      color1: "bg-black",    
      color2: "red",
    },
    {
      discountBtn: false,
      discountPrice: 40,
      trashIcon: false,
      heartIcon: true,
      eyeIcon: true,
      src: "/jack.png",
      Heading: "Quilted Satin Jacket",
      price: 660,
      star: 5,
      reviews: 55,
      colorDiv: true,
      color1: "bg-black",
      color2: "orange",
    }
  ]